# -*- coding: utf-8 -*-
"""179_data_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jb9H9Ce5m3exySYowEe7_xSw0mSC6y-t
"""

import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("CleanData").getOrCreate()

# Read in and show initial data/dimensions
df = spark.read.csv("ngrams1.csv", sep ="\t", header=False, inferSchema=True)
df.show(10)
print("Number of rows:", df.count())

# Add column names
col_name = ["word", "year", "match_count", "page_count", "volume_count"]
df = df.toDF(*col_name)
df.show(10)

# Shows the schema of the dataset
df.printSchema()

# Check and drop duplicate rows if there are any
# If number of rows match original, no duplicate rows are present

print("Number of distinct rows:", df.distinct().count())

# Check and remove any null data if there are any
# Code below displays the rows that are null, if none list is empty

print("Null words:", df.filter(df.word.isNull()).collect())
print("Null year:", df.filter(df.year.isNull()).collect())
print("Null match_count:", df.filter(df.match_count.isNull()).collect())
print("Null page_count:", df.filter(df.page_count.isNull()).collect())
print("Null volume_count:", df.filter(df.volume_count.isNull()).collect())

# Remove numerical values and symbols
import pyspark.sql.functions as sf

df = df.filter(sf.rlike('word', sf.lit(r"^[A-Za-z']+$")))
df.show()
print("Number of rows:", df.count())

# get most popular word of each year
# how to improve: get most popular word that's not a conjunction/ pronoun/ etc

a = df.alias("a")
b = df.alias("b")
df2 = b.groupBy(b.year).agg(sf.max(b.match_count).alias("highestCount"))
(
    a
      .join(df2, [a.year == df2.year, a.match_count == df2.highestCount])
      .select(a.year, df2.highestCount, a.word)
      .sort(sf.desc(df.year))
      .show()
)


# get published instances of word per year for a specified word

trend = df.alias("trend")

matchWord = "DATABASE"
trend.select(trend.word, trend.year, trend.match_count).filter(trend.word == matchWord).sort(trend.year).show()

# make trend graph for word
import matplotlib.pyplot as plt
trend.plot(x="year",y="match_count")

