# -*- coding: utf-8 -*-
"""179_data_clean.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Jb9H9Ce5m3exySYowEe7_xSw0mSC6y-t
"""

import pyspark
from pyspark.sql import SparkSession

spark = SparkSession.builder.appName("CleanData").getOrCreate()

# Read in and show initial data/dimensions
df = spark.read.csv("ngram.csv", sep ="\t", header=False, inferSchema=True)
df.show(10)
print("Number of rows:", df.count())

# Add column names
col_name = ["word", "year", "match_count", "page_count", "volume_count"]
df = df.toDF(*col_name)
df.show(10)

# Shows the schema of the dataset
df.printSchema()

# Check and drop duplicate rows if there are any
# If number of rows match original, no duplicate rows are present

print("Number of distinct rows:", df.distinct().count())

# Check and remove any null data if there are any
# Code below displays the rows that are null, if none list is empty

print("Null words:", df.filter(df.word.isNull()).collect())
print("Null year:", df.filter(df.year.isNull()).collect())
print("Null match_count:", df.filter(df.match_count.isNull()).collect())
print("Null page_count:", df.filter(df.page_count.isNull()).collect())
print("Null volume_count:", df.filter(df.volume_count.isNull()).collect())

# Remove numerical values and symbols
import pyspark.sql.functions as sf

df = df.filter(sf.rlike('word', sf.lit(r"^[A-Za-z']+$")))
df.show()
print("Number of rows:", df.count())